CREATE TABLE Disciplina_Oferta (
	
	id INT IDENTITY PRIMARY KEY,
	--CHAVE ESTRANGEIRA 
	CONSTRAINT FK_COORDENADOR FOREIGN KEY (id_coordenador) REFERENCES usuario(id),
	DtInicioMatricula2 VARCHAR(50),
	DtFimMatricula2   VARCHAR(20),

	CONSTRAINT FK_DISCIPLINA FOREIGN KEY (id_disciplina) REFERENCES disciplinas(id),
	CONSTRAINT FK_CURSO		 FOREIGN KEY (id_curso)		 REFERENCES curso(id),
	ANO INT,
	CHECK (ANO >= 1900 and ANO <= 2100),
	SEMESTRE INT
	CHECK (SEMESTRE >= 1 and SEMESTRE <= 2),
	TURMA VARCHAR (50),
	CHECK ( TURMA = '^[A-Z]{3}-\d{4}$'),
	CONSTRAINT FK_id_PROFESSOR FOREIGN KEY (id_professor) REFERENCES professor(id),
	METODOLOGIA			VARCHAR(100),
	RECURSOS			VARCHAR(50),
	CRITERIO_AVALIACAO	VARCHAR(50),
	PLANO_DE_AULAS		VARCHAR(100)




)